name: bookgrow_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  barcode_scan2: ^4.1.6
  http: ^0.13.3
  xml: ^6.1.0
  logger: ^1.1.0
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img_none.png
